Update zh_TW.json
ciderapp/Cider pull request #1076
Opened 2022-05-24 12:42 UTC by jay900604

Update TW language.

2022-05-24 13:25 UTC, yazninja commented
can you add term.stop, its new

2022-05-25 00:20 UTC, maikirakiwi requested changes

2022-05-25 00:20 UTC, maikirakiwi commented on src/i18n/zh_TW.json
> +  "term.enableRepeatOne": "取消單曲循環",
啟用單曲循環

2022-05-25 00:23 UTC, jay900604 commented on src/i18n/zh_TW.json
> +  "term.enableRepeatOne": "取消單曲循環",
我覺得多了"啟用"似乎有多餘，因為他是點擊下去就開啟。若要新增的話，請將"啟用"改成"開啟"。

2022-05-25 02:04 UTC, jay900604 reviewed
優化 "term.enableShuffle"和"term.repeat"用詞，以及音訊實驗室部分功能的用詞.

2022-05-28 02:16 UTC, maikirakiwi approved these changes

2022-05-28 02:17 UTC, maikirakiwi commented
十分感谢！
Thank you so much!

2022-05-28 02:17 UTC, merged