Update ja_JP translation
ciderapp/Cider pull request #1162
Opened 2022-06-12 09:30 UTC by YTJVDCM

I updated and translated new strings.

2022-06-12 15:13 UTC, maikirakiwi requested changes

2022-06-12 15:13 UTC, maikirakiwi commented on src/i18n/ja_JP.json
> +  "oobe.visual.layout.text": "Ciderには2つの異なるウィンドウレイアウトがあります。\nMarverickはウィンドウ上部にプレイヤーのある、iTunes風のレイアウトです。\nMojaveはCider Collectiveによって作成された新たな試作品です。\n\nこれらのレイアウトはいつでも設定から変更することができます。",
Marverick-> Maverick

2022-06-12 15:13 UTC, maikirakiwi commented on src/i18n/ja_JP.json
> +  "settings.option.audio.audioLab.description": "Ciderのために開発された室内音響設定の数々",
ちょっと意味が微妙に違う。
「in-house developed」って室内の意味ではなく、More like 自社開発?

I think.

2022-06-13 03:43 UTC, YTJVDCM commented
Thanks for your request.
I misunderstood the meaning of the word.
And I fixed it.

2022-06-13 04:10 UTC, maikirakiwi commented
迅速に対応いただきありがとうございます。
I will be merging this now.

2022-06-13 04:10 UTC, merged