Update zh_CN.json
ciderapp/Cider pull request #1340
Opened 2022-08-02 02:37 UTC by sakura0224

2022-08-04 07:33 UTC, maikirakiwi requested changes

2022-08-04 07:33 UTC, maikirakiwi commented on src/i18n/zh_CN.json
> +  "oobe.visual.suggestingThemes.community2.text": "经典的大水果布局。",
大水果是个什么牛马

2022-08-04 07:42 UTC, sakura0224 commented on src/i18n/zh_CN.json
> +  "oobe.visual.suggestingThemes.community2.text": "经典的大水果布局。",
草，我看jp翻的巨大果物，spanish的frutas grandes，一度怀疑我翻错了，我改回去

2022-08-04 23:17 UTC, merged

2022-08-07 01:18 UTC, maikirakiwi commented
approved