Added more customizability to the Discord Rich Presence Plugin on Cider (Buttons)
ciderapp/Cider pull request #725
Opened 2022-03-28 11:24 UTC by Monochromish

Now, People can choose whether to hide buttons on their rich presence (Listen on Cider & View on Apple Music)

2022-03-28 12:25 UTC, coredev-uk requested changes
A fuck ton of merge comments, I've only commented on a few of them but there's more. I suggest you restore your i18n files to source.

2022-03-28 12:25 UTC, coredev-uk commented on src/i18n/en_US.json
> +<<<<<<< Updated upstream
Fix ur merge comments

2022-03-28 12:25 UTC, coredev-uk commented on src/i18n/en_US.json
> +=======
here again

2022-03-28 12:25 UTC, coredev-uk commented on src/i18n/en_US.json
> +>>>>>>> Stashed changes
here

2022-03-28 12:25 UTC, coredev-uk commented on src/i18n/source/en_US.json
> +<<<<<<< Updated upstream
here

2022-03-28 12:25 UTC, coredev-uk commented on src/i18n/source/en_US.json
> +=======
here

2022-03-28 12:25 UTC, coredev-uk commented on src/main/plugins/discordrpc.ts
> +=======
c'mon

2022-03-28 12:25 UTC, coredev-uk commented on src/main/plugins/discordrpc.ts
> +<<<<<<< Updated upstream
check

2022-03-28 12:50 UTC, rowbawts commented
I'd love to see this as I believe it will contribute to a cleaner look for the app's integration.

2022-03-28 12:58 UTC, Monochromish commented
Sorry for the inconvenience @coredev-uk; I've reviewed the comments.

2022-03-29 04:53 UTC, maikirakiwi commented
Check branch conflict

2022-03-29 22:24 UTC, coredev-uk requested changes
I suggest you remove the formatting that you have done on various files, it's hard to track what code you are contributing when there are large diffs. Sorry.

2022-03-30 09:34 UTC, coredev-uk commented
Requested close, pending new PR with the feature from the author.

2022-03-30 09:34 UTC, closed without merging