Fix now playing context menu not rendering from 'songs' page
ciderapp/Cider pull request #960
Opened 2022-04-30 02:24 UTC by umbreon22

There are times where nowPlaying._context is undefined, so I added a check around it's presence for enabling the 'showInMusic' menu item.

One way to replicate the issue:

- Navigate to the songs page
- Shuffle songs
- Right click the now playing bar OR click the bar's ellipsis in attempt to open a context menu

2022-04-30 03:33 UTC, cryptofyre commented
Could you reopen this PR but for the development branch? Main usually gets overwritten.

2022-04-30 11:53 UTC, Amaru8 requested changes
Please set the `develop` branch of `ciderapp/Cider` as the base of this Pull Request.

2022-04-30 19:02 UTC, Amaru8 approved these changes

2022-05-01 17:00 UTC, cryptofyre approved these changes

2022-05-01 17:01 UTC, merged